SELECT T1.ITEMID,INVENTSITEID AS SITE, INVENTLOCATIONID WHAREHOUSE,  
case REQPOTYPE when 1 then 'PRODUCTION'
			   when 2 then 'TRANSFER'	
			   when 0 then 'PURCHASE ORDER'	
			   else cast(REQPOTYPE as nvarchar)
end [PLANNED ORDER TYPE] ,
REQGROUPID, INVENTLOCATIONIDREQMAIN [MAIN WAREHOUSE]

--T1.COVINVENTDIMID,T1.TIMEFENCEFIELDSACTIVE,T1.COVRULE,T1.COVPERIOD,T1.MININVENTONHAND,T1.MAXINVENTONHAND,T1.LEADTIMEPURCHASE,T1.LEADTIMEPRODUCTION,T1.AUTHORIZATIONTIMEFENCE,T1.VENDID,T1.MINSAFETYKEYID,T1.MINSATISFY,T1.REQGROUPID,T1.REQPOTYPE,T1.MAXPOSITIVEDAYS,T1.MAXNEGATIVEDAYS,T1.COVTIMEFENCE,T1.MAXSAFETYKEYID,T1.INVENTLOCATIONIDREQMAIN,T1.MINSAFETYPERIOD,T1.CALENDARDAYSPRODUCTION,T1.CALENDARDAYSPURCHASE,T1.LEADTIMETRANSFER,T1.CALENDARDAYSTRANSFER,T1.LEADTIMETRANSFERACTIVE,T1.LEADTIMEPRODUCTIONACTIVE,T1.LEADTIMEPURCHASEACTIVE,T1.COVFIELDSACTIVE,T1.REQPOTYPEACTIVE,T1.ITEMCOVFIELDSACTIVE,T1.LOCKINGTIMEFENCE,T1.EXPLOSIONTIMEFENCE,T1.CAPACITYTIMEFENCE,T1.PMFPLANNINGITEMID,T1.PMFPLANPRIORITYCURRENT,T1.PMFPLANPRIORITYDATECHANGED,T1.PMFPLANPRIORITYDEFAULT,T1.TIMEFENCEBACKREQUISITION,T1.ONHANDACTIVE,T1.ONHANDCONSUMPTIONSTRATEGY,T1.RECVERSION,T1.PARTITION,T1.RECID 
FROM REQITEMTABLE T1 CROSS JOIN 
	 INVENTDIM T2 
WHERE (((T1.PARTITION=5637144576) AND (T1.DATAAREAID='220')) --AND (T1.ITEMID='392625HSIL')
) 
  AND (((T2.PARTITION=5637144576) AND (T2.DATAAREAID='220')) 
  AND ((((((((((((((((T2.INVENTDIMID=T1.COVINVENTDIMID) )))))))))))))))) 
  
						