WITH EXPBOM (
    DATAAREAID,
    BOM,
    PRODUCT,
    MATERIAL,
    BOMDEPTH,
    BOMPATH,
	BOMQTY,
	UNITID
) AS (
    SELECT
			BV.DATAAREAID,
			BV.BOMID,
			BV.ITEMID,
			B.ITEMID,
			1,
			CONVERT(VARCHAR(MAX), BV.ITEMID + '|' + B.ITEMID) AS BOMPATH,
			cast (b.BOMQTY as decimal(16,8)) BOMQTY,
			b.UNITID
    FROM BOMVERSION BV
    JOIN INVENTTABLE IBV	ON IBV.DATAAREAID = BV.DATAAREAID        AND IBV.ITEMID = BV.ITEMID
    JOIN BOM B				ON B.DATAAREAID = BV.DATAAREAID        AND B.BOMID = BV.BOMID
    JOIN INVENTTABLE IB     ON IB.DATAAREAID = B.DATAAREAID        AND IB.ITEMID = B.ITEMID
    WHERE BV.APPROVED = 1
        AND BV.ACTIVE = 1
        AND BV.FROMDATE < GETDATE()
        AND (BV.TODATE = '01-01-1900' OR BV.TODATE >= GETDATE())
        AND B.FROMDATE < GETDATE()
        AND (B.TODATE = '01-01-1900' OR B.TODATE >= GETDATE())
		--AND BV.itemid IN ('17-594B','03-4262','03-4261R1','6430','P0800002-A','03-5310R5','03-5314','03-2937','HSBC','03-4202R3','992667H','R470-0260','392667H','R470-0260','03-5750','02-0478','992667H-SIL','392667H-SIL','03-2094','100-6120')
    UNION ALL
    SELECT
        BV.DATAAREAID,
        BV.BOMID,
        BV.ITEMID,
        EB.MATERIAL,
        EB.BOMDEPTH + 1,
        CONVERT(VARCHAR(MAX), BV.ITEMID + '|' + EB.BOMPATH) AS BOMPATH,
		CAST(B.BOMQTY * CAST(EB.BOMQTY AS DECIMAL(16,8)) AS DECIMAL(16,8)),
		EB.UNITID
    FROM BOMVERSION BV
    JOIN INVENTTABLE IBV	ON IBV.DATAAREAID	= BV.DATAAREAID	AND IBV.ITEMID	= BV.ITEMID
    JOIN BOM B				ON B.DATAAREAID		= BV.DATAAREAID	AND B.BOMID		= BV.BOMID
    JOIN EXPBOM EB			ON EB.DATAAREAID	= B.DATAAREAID	AND EB.PRODUCT	= B.ITEMID
    WHERE BV.APPROVED = 1	
		AND BV.ACTIVE = 1
        AND BV.FROMDATE < GETDATE()
        AND (BV.TODATE = '01-01-1900' OR BV.TODATE >= GETDATE())
        AND B.FROMDATE < GETDATE()
        AND (B.TODATE = '01-01-1900' OR B.TODATE >= GETDATE())
)
SELECT * FROM EXPBOM
--where product = '100-6120' and BOMQTY > 0.0000000000000000
--ORDER BY 4