WITH EXPBOM (
    DATAAREAID,
    BOM,
    PRODUCT,
    MATERIAL,
    BOMDEPTH,
    BOMPATH,
	BOMQTY,
	UNITID
) AS (
    SELECT
			BV.DATAAREAID,
			BV.BOMID,
			BV.ITEMID,
			B.ITEMID,
			1,
			CONVERT(VARCHAR(MAX), BV.ITEMID + '|' + B.ITEMID) AS BOMPATH,
			b.BOMQTY,
			b.UNITID
    FROM BOMVERSION BV
    JOIN INVENTTABLE IBV	ON IBV.DATAAREAID = BV.DATAAREAID        AND IBV.ITEMID = BV.ITEMID
    JOIN BOM B				ON B.DATAAREAID = BV.DATAAREAID        AND B.BOMID = BV.BOMID
    JOIN INVENTTABLE IB     ON IB.DATAAREAID = B.DATAAREAID        AND IB.ITEMID = B.ITEMID
    WHERE BV.APPROVED = 1
        AND BV.ACTIVE = 1
        AND BV.FROMDATE < GETDATE()
        AND (BV.TODATE = '01-01-1900' OR BV.TODATE >= GETDATE())
        AND B.FROMDATE < GETDATE()
        AND (B.TODATE = '01-01-1900' OR B.TODATE >= GETDATE())
		
    UNION ALL
    SELECT
        BV.DATAAREAID,
        BV.BOMID,
        BV.ITEMID,
        EB.MATERIAL,
        EB.BOMDEPTH + 1,
        CONVERT(VARCHAR(MAX), BV.ITEMID + '|' + EB.BOMPATH) AS BOMPATH,
		B.BOMQTY,
		B.UNITID
    FROM BOMVERSION BV
    JOIN INVENTTABLE IBV	ON IBV.DATAAREAID	= BV.DATAAREAID	AND IBV.ITEMID	= BV.ITEMID
    JOIN BOM B				ON B.DATAAREAID		= BV.DATAAREAID	AND B.BOMID		= BV.BOMID
    JOIN EXPBOM EB			ON EB.DATAAREAID	= B.DATAAREAID	AND EB.PRODUCT	= B.ITEMID
    WHERE BV.APPROVED = 1	
		AND BV.ACTIVE = 1
        AND BV.FROMDATE < GETDATE()
        AND (BV.TODATE = '01-01-1900' OR BV.TODATE >= GETDATE())
        AND B.FROMDATE < GETDATE()
        AND (B.TODATE = '01-01-1900' OR B.TODATE >= GETDATE())
)
SELECT * FROM EXPBOM
--where product = '0076'@LASDFGSDF