/*
SELECT ITEMID, BOMID FROM BOMVERSION WHERE ITEMID = '0076' AND ACTIVE = 1 AND	APPROVED = 1

SELECT B.ITEMID, V.BOMID
FROM BOM B 
INNER JOIN INVENTTABLE I ON B.ITEMID = I.ITEMID
 LEFT JOIN  BOMVERSION V ON V.ITEMID = B.ITEMID AND ACTIVE = 1 AND	APPROVED = 1 
WHERE B.BOMID = '0076 R1'  
*/
--;
DECLARE @ITEM  NVARCHAR(20) = '28-0018';
DECLARE @QTY  decimal(18,2) = 1000;

WITH EXPBOM(
    MAIN,
	ITEMID, 
	BOMID,
	BOMQTY,
	Unit 
) AS (
	SELECT ITEMID AS Main,ITEMID, BOMID, CAST (@QTY as decimal(16,8)) , cast(' ' as nvarchar(10))
	FROM BOMVERSION WHERE ITEMID = @ITEM AND ACTIVE = 1 AND	APPROVED = 1
	UNION ALL
	SELECT X.ITEMID AS MAIN, B.ITEMID, 
					(
						SELECT BOMID  FROM  BOMVERSION V WHERE V.ITEMID = B.ITEMID AND ACTIVE = 1 AND	APPROVED = 1 
					)	 AS BOMID,
					CAST(B.BOMQTY * CAST(X.BOMQTY AS DECIMAL(16,8)) AS DECIMAL(16,8)),
					b.UNITID	
	FROM BOM B 
	INNER JOIN INVENTTABLE I ON B.ITEMID = I.ITEMID	 
     CROSS JOIN EXPBOM X
	WHERE B.BOMID = X.BOMID

)
Select * FROM EXPBOM
where	
		--ITEMID like '03%' AND
		BOMID is null and BOMQTY > 0
order by 2