DECLARE @prodOrder nvarchar(7) = 'AAAB855'    

SELECT BOM.*, QTYBOMCALC - ISNULL(QTY,0) PENDIENTE_POR_SURTIR
FROM 
		(	
		SELECT PRODID,ITEMID, cast(QTYBOMCALC as decimal(16,0)) QTYBOMCALC
		FROM PRODBOM
		WHERE PRODID LIKE @prodOrder
			  AND BOMQTY > 0 
			  AND ITEMID NOT IN('WIP-Labor','WIP-Material','WIP-Overhead')
		) BOM 
LEFT JOIN
		(
		SELECT REFERENCEID, ITEMNUM, CAST(SUM(INVENTQTY) * -1 as decimal(16,0)) QTY
		FROM ANGBPMINVENTORYTRANSEXTRACT
		WHERE   REFERENCEID LIKE @prodOrder	
				AND INVENTREFCATEGORY = 'ProductionLine'
				AND (
						INVENTISSUESTATUS = 'Sold' AND	INVENTRECEIPTSTATUS = 'None'
						OR
						INVENTISSUESTATUS = 'None' AND	INVENTRECEIPTSTATUS = 'Purchased'
					)
		group by REFERENCEID, ITEMNUM
		) TRN ON BOM.PRODID = TRN.REFERENCEID AND BOM.ITEMID = TRN.ITEMNUM
Order by 1,2



