SELECT 
SALESORDER	,SALESLINENUM	,ITEMNUM	,QTYORDERED, SALESPRICE, SALESQTY,
SALESUOM, CURRENCYCODE,	SALESLINEAMOUNT, SALESNAME, INVOICEQTY,	INVOICELINEAMOUNT,
SALESSTATUS,	SALESTYPE,INVOICEPRICE
FROM ANGBPMSALESEXTRACT
WHERE ITEMNUM IN ('SXPD2B40336','SXPD2B40536','SXPD2B42336')
