select PT.PRODPOOLID [POOL],
       A.PRODID,
	   PT.itemid ITEMNUM,
	   A.LAST_RPT_FINISH,
	   B.OPRID LAST_RPT_NAME,
	   (SELECT CAST(ISNULL(SUM(TRN.QTYGOOD),0) as numeric(12,2)) FROM PRODROUTETRANS TRN WHERE TRANSREFID = A.PRODID and TRANSTYPE = 1 AND TRN.OPRNUM = LAST_RPT_FINISH) LAST_RPT_GOOD_QTY,
       CASE PRODSTATUS
			 WHEN 0 THEN  'Created'
			 WHEN 1 THEN  'CostEstimated'
			 WHEN 2 THEN  'Scheduled'
			 WHEN 3 THEN  'Released'
			 WHEN 4 THEN  'StartedUp'
			 WHEN 5 THEN  'ReportedFinished'
			 WHEN 7 THEN  'Ended'
		END PRODSTATUS,	
		(
		SELECT COUNT(1)
		FROM INVENTQUARANTINEORDER qo
		WHERE	pT.ITEMID=qo.ITEMID and pt.PRODID=Qo.TRANSREFID and Pt.INVENTTRANSID=Qo.INVENTTRANSIDREF
				and Status  <> ALL (select 3)
		) QuarantineOrdersOpen, 
		(
		SELECT CAST(ISNULL(SUM(QTY),0) as numeric(12,2))
		FROM INVENTQUARANTINEORDER qo
		WHERE	pT.ITEMID=qo.ITEMID and pt.PRODID=Qo.TRANSREFID and Pt.INVENTTRANSID=Qo.INVENTTRANSIDREF
				and Status  <> ALL (select 3)
		) QuarantineOpenQty, 
		(
		SELECT COUNT(1)
		FROM INVENTQUARANTINEORDER qo
		WHERE	pT.ITEMID=qo.ITEMID and pt.PRODID=Qo.TRANSREFID and Pt.INVENTTRANSID=Qo.INVENTTRANSIDREF
				and Status  = ALL (select 3)
		) QuarantineOrdersEnded, 
		(
		SELECT CAST(ISNULL(SUM(QTY),0) as numeric(12,2))
		FROM INVENTQUARANTINEORDER qo
		WHERE	pT.ITEMID=qo.ITEMID and pt.PRODID=Qo.TRANSREFID and Pt.INVENTTRANSID=Qo.INVENTTRANSIDREF
				and Status  = ALL (select 3)
		) QuarantineEndedQty, 
		(
		SELECT CAST(ISNULL(SUM(T1.QTY),0) as numeric(12,2)) TOTAL
		FROM INVENTTRANS T1 INNER JOIN 
			 INVENTTRANSORIGINPRODTABLE T2 ON PRODORDERID = A.prodid  AND T1.INVENTTRANSORIGIN = T2.INVENTTRANSORIGIN
		WHERE STATUSRECEIPT in(1,2) or STATUSISSUE = 1
		) ReportedAsFinishedQty,
	   CAST(PT.QtySched as numeric(12,2)) [SCHEDULED],
	   CAST(PT.QtyStUp as numeric (12,2)) [STARTED],
	   DATEADD(hh, DATEDIFF(hh, GETDATE(), GETUTCDATE())*-1, PT.MODIFIEDDATETIME) LAST_DATE,
	   (SELECT CAST(max(INVENTDATEPHYSICAL) AS DATE)
		FROM    DBO.ANGBPMINVENTORYTRANSEXTRACT AS T1 
		WHERE   INVENTISSUESTATUS IN('Deducted','Sold')
				AND SITE = 'TJ'
				AND WAREHOUSE IN('TJ-MAT','TJ-MAIN')
				AND INVENTREFCATEGORY in('ProductionLine')
				AND T1.REFERENCEID = A.prodid) [WH_PICKED_ON],	   	   
	   (SELECT OPRNUMNEXT from PRODROUTE t1 where t1.prodid = A.prodid and A.LAST_RPT_FINISH = t1.OPRNUM  ) NextOP,
	   DATEDIFF(DD,PT.MODIFIEDDATETIME,GETUTCDATE()) Inactive_days	   	   
FROM  (
		SELECT	 PRODID, 
				CASE max(OPRFINISHED) 
						WHEN  0  THEN MIN(OPRNUM)
						ELSE		  ( SELECT MAX(OPRNUM) from  PRODROUTE R1 WHERE R1.PRODID = R0.PRODID AND OPRFINISHED =  1)
				END  LAST_RPT_FINISH
		FROM PRODROUTE R0				
		GROUP BY PRODID
	  ) A
LEFT JOIN PRODROUTE B	ON	A.prodid = B.prodid AND A.LAST_RPT_FINISH = B.OPRNUM
LEFT JOIN PRODTABLE PT ON  PT.PRODID = A.PRODID  
Order by PT.MODIFIEDDATETIME desc


