SELECT	A.PRODID,       
		 CASE PRODSTATUS
			 WHEN 0 THEN  'CREATED'
			 WHEN 1 THEN  'COSTESTIMATED'
			 WHEN 2 THEN  'SCHEDULED'
			 WHEN 3 THEN  'RELEASED'
			 WHEN 4 THEN  'STARTEDUP'
			 WHEN 5 THEN  'REPORTEDFINISHED'
			 WHEN 7 THEN  'ENDED'
		 END									PRODSTATUS, 
		CAST(MIN(B.DATEWIP) AS DATE)			INITIAL_DATE, 
		CAST(MAX(B.DATEWIP) AS DATE)			END_DATE,
		COUNT(DISTINCT J.JOURNALID)				PICKLISTSNOTPOSTED,
		MAX(A.OPRNUM)							LASTOP,
		ISNULL(STUFF(( 
				SELECT DISTINCT TOP 100 PERCENT  ',' + INVENTLOCATIONID 
				FROM  PRODJOURNALTABLE JT
				INNER JOIN DBO.PRODJOURNALBOM JB  ON  JT.JOURNALID = JB.JOURNALID AND JT.POSTED = 0
				INNER JOIN INVENTDIM INV ON JB.INVENTDIMID = INV.INVENTDIMID				 
				WHERE JB.PRODID = A.PRODID
				ORDER BY ',' + INVENTLOCATIONID
				FOR XML PATH('')
				), 1, 1, '') + '','') AS LOCATION
FROM PRODROUTE  A 
INNER JOIN	PRODTABLE P			ON A.PRODID = P.PRODID	
LEFT JOIN	PRODROUTETRANS B	ON A.PRODID = TRANSREFID AND TRANSTYPE = 1 AND A.OPRNUM = B.OPRNUM
LEFT JOIN	INVENTBATCH BT		ON A.PRODID = BT.INVENTBATCHID AND P.ITEMID = BT.ITEMID
LEFT JOIN   PRODJOURNALTABLE J	ON A.PRODID = J.PRODID AND NUMOFLINES >=1 AND POSTED = 0
GROUP BY A.PRODID,A.OPRFINISHED, PRODSTATUS, PRODDATE
HAVING   A.OPRFINISHED = 1         
		 AND PRODSTATUS = 4
		 AND COUNT(DISTINCT J.JOURNALID) > 0
		 AND (SELECT OPRNUMNEXT FROM PRODROUTE T1 WHERE T1.PRODID = A.PRODID AND MAX(A.OPRNUM) = T1.OPRNUM  ) = 0		 
ORDER BY 5 DESC
