SELECT A.PRODID,
       A.OPRFINISHED, 	   
       CASE PRODSTATUS 
			WHEN 7 THEN 'ENDED' 
			ELSE 'WIP' 
	   END										PRODSTATUS,
	   MIN(B.DATEWIP)							INITIAL_DATE, 
	   MAX(B.DATEWIP)							END_DATE,
	   PRODDATE									MANUFACTURING_DATE,
	   DATEDIFF(D,MAX(B.DATEWIP) ,PRODDATE  )	FUTURE,
	   DATEDIFF(D,PRODDATE,MIN(B.DATEWIP)  )	PASS
FROM PRODROUTE  A 
INNER JOIN	PRODTABLE P			ON A.PRODID = P.PRODID	
LEFT JOIN	PRODROUTETRANS B	ON A.PRODID = TRANSREFID AND TRANSTYPE = 1 AND A.OPRNUM = B.OPRNUM
LEFT JOIN	INVENTBATCH BT		ON A.PRODID = BT.INVENTBATCHID AND p.ITEMID = BT.ITEMID
GROUP BY A.PRODID,A.OPRFINISHED, PRODSTATUS, PRODDATE
HAVING   A.OPRFINISHED = 1         
		 AND PRODSTATUS = 7		 
ORDER BY 6 DESC


