	SELECT	DISTINCT
			it.ITEMID																				ITEM, 
			trans.NAME																				[DESCRIPTION], 
			CASE eprd.ProductType	WHEN 1 THEN 'ITEM' 
									ELSE 'Service' 
			END																						[ITEM TYPE],
			CASE iexp.ProductSubtype	WHEN 1 THEN 'PRODUCT' 
										WHEN 2 THEN 'PRODUCT MASTER'
										WHEN 3 THEN 'PRODUCT VARIANT'
										ELSE '' 
			END																						[ITEM SUBTYPE],
			it.ItemClassId																			[ITEM CLASS],
			invA.INVENTLOCATIONID																	WAREHOUSE, 
			req.MaxNegativeDays																		[NEGATIVE DAYS],
			--req.COVFIELDSACTIVE,
			req.leadTimePurchase																	[PURCHASE LEAD TIME],
			(SELECT UNITID from InventTableModule	where itemid = it.ITEMID and moduletype = 0)	[INV UNIT],
			(SELECT UNITID from InventTableModule	where itemid = it.ITEMID and moduletype = 1)	[PURCHASE UNIT],
			(SELECT UNITID from InventTableModule	where itemid = it.ITEMID and moduletype = 2)	[SALES UNIT],
			(SELECT PRICE  from InventTableModule	where itemid = it.ITEMID and moduletype  = 1)	[PURCH_PRICE],
			Aprroved_Vendors.NAME																	[VENDOR NAME],
			DOS.DEFAULTORDERTYPE																	[ORDER TYPE],
			DOS.MULTIPLEQTY																			[PURCHASE MULTIPLE],
			DOS.LOWESTQTY																			[PURCHASE MOQ],
			case it.PMFPRODUCTTYPE
				when 4 then 'BOM'
				else 'None'
			end																						[PRODUCTION TYPE],
			it.ItemBuyerGroupId																		BUYER
	FROM	ECORESPRODUCT				eprd WITH(NOLOCK)	CROSS JOIN 
			INVENTTABLE					it	 WITH(NOLOCK)	CROSS JOIN 
			ECORESPRODUCTTRANSLATION	trans WITH(NOLOCK)	CROSS JOIN 
			INVENTTABLEEXPANDED			iexp WITH(NOLOCK)	LEFT JOIN
			ReqItemTable				req  WITH(NOLOCK) ON req.ITEMID			= it.ITEMID				LEFT JOIN
			INVENTDIM					invA WITH(NOLOCK) ON invA.INVENTDIMID	= req.COVINVENTDIMID	LEFT JOIN
			(	SELECT distinct ITEMID, PDSAPPROVEDVENDOR,name 
				from	PdsApprovedVendorList	WITH(NOLOCK)											INNER JOIN 
						VendTable				WITH(NOLOCK)	on PDSAPPROVEDVENDOR	= ACCOUNTNUM	INNER JOIN
						DirPartyTable	dp		WITH(NOLOCK)	on PARTY				= dp.RECID
			) Aprroved_Vendors  ON it.ITEMID				= Aprroved_Vendors.ITEMID					LEFT JOIN
			(
				SELECT 
					T1.ITEMID,
					CASE DEFAULTORDERTYPE
						WHEN 0 THEN 'Purchase order'
						WHEN 1 THEN 'Production'
						ELSE CAST(DEFAULTORDERTYPE AS NVARCHAR) 
					End DEFAULTORDERTYPE
					, T1.MULTIPLEQTY, T1.LOWESTQTY	
				FROM	INVENTITEMPURCHSETUP		T1 WITH(NOLOCK) CROSS JOIN 
						INVENTDIM					T2 WITH(NOLOCK) CROSS JOIN 
						INVENTDIM					T3 WITH(NOLOCK) CROSS JOIN 
						INVENTITEMINVENTSETUP		T4 WITH(NOLOCK) CROSS JOIN 
						INVENTITEMSALESSETUP		T5 WITH(NOLOCK) LEFT OUTER JOIN 
						INVENTITEMSETUPSUPPLYTYPE	T6 WITH(NOLOCK)	ON	T6.PARTITION=T1.PARTITION AND T1.ITEMID=T6.ITEMID AND 
																		T1.DATAAREAID=T6.ITEMDATAAREAID 
						CROSS JOIN INVENTDIM T7 WITH(NOLOCK)		CROSS JOIN INVENTDIM T8 WITH(NOLOCK)
				WHERE	T1.PARTITION=5637144576 AND T1.DATAAREAID=220 AND T1.INVENTDIMID IN ('DIM000002','DIM124741') AND
						T1.INVENTDIMIDDEFAULT <> 'DIM000003' AND
						--T1.ITEMID='02-0235' AND 
						T6.DEFAULTORDERTYPE = 0 AND
						T2.PARTITION=T1.PARTITION AND T2.DATAAREAID=T1.DATAAREAID AND T1.INVENTDIMID=	T2.INVENTDIMID AND 
						T3.PARTITION=T1.PARTITION AND T3.DATAAREAID=T1.DATAAREAID AND T1.INVENTDIMIDDEFAULT=T3.INVENTDIMID AND 
						T4.PARTITION=T1.PARTITION AND T4.DATAAREAID=T1.DATAAREAID AND T1.ITEMID=T4.ITEMID AND T1.INVENTDIMID=T4.INVENTDIMID AND 
						T5.PARTITION=T1.PARTITION AND T5.DATAAREAID=T1.DATAAREAID AND T1.ITEMID=T5.ITEMID AND T1.INVENTDIMID=T5.INVENTDIMID AND 
						T7.PARTITION=T1.PARTITION AND T7.DATAAREAID=T1.DATAAREAID AND T4.INVENTDIMIDDEFAULT=T7.INVENTDIMID AND 
						T8.PARTITION=T1.PARTITION AND T8.DATAAREAID=T1.DATAAREAID AND T5.INVENTDIMIDDEFAULT=T8.INVENTDIMID 
			) DOS ON it.ITEMID				= DOS.ITEMID
	WHERE eprd.DISPLAYPRODUCTNUMBER = it.ITEMID 
		 -- AND it.ITEMID				= '02-0235'
		  AND trans.PRODUCT			= it.PRODUCT 
		  AND iexp.ItemId			= it.ITEMID
    ORDER BY 1		  
		  
		  
		


		 -- INVENTDIM where INVENTDIMID IN ('AllBlank','DIM000002','DIM124741')
 /*
		  PdsApprovedVendorList where ITEMID				= '01-0087'
		  SELECT PARTY  from VendTable where  ACCOUNTNUM = 'B0180' 
		  SELECT name from DirPartyTable dp where RECID = 		  5637314889

		  SELECT PDSAPPROVEDVENDOR,name 
		  from	PdsApprovedVendorList										inner join 
				VendTable			on PDSAPPROVEDVENDOR	= ACCOUNTNUM	inner join
				DirPartyTable	dp	on PARTY				= dp.RECID

				*/

		  
