--(InventItemPurchSetup,InventDim,InventDim,InventItemInventSetup,InventItemSalesSetup,InventItemSetupSupplyType,InventDim,InventDim) 

SELECT  T0.ITEMID, 
		XX.INVENTSITEID		[PURCHASA SITE], 
		T1.STOPPED			[STOPPED FOR PURCHASING], 
		XX2.INVENTSITEID	[INVENTORY SITE], 
		T2.STOPPED			[STOPPED FOR INVENTORING],
		XX3.INVENTSITEID	[SALES SITE],
		T3.STOPPED			[STOPPED FOR SALLING] 
FROM inventtable T0 
LEFT JOIN INVENTITEMPURCHSETUP T1  on t0.itemid = t1.itemid 
LEFT JOIN INVENTITEMINVENTSETUP T2 on t1.itemid = t2.itemid and t1.INVENTDIMID = t2.INVENTDIMID
LEFT JOIN INVENTITEMSALESSETUP T3 on t2.itemid = t3.itemid  and t2.INVENTDIMID = t3.INVENTDIMID
LEFT JOIN INVENTDIM XX on xx.INVENTDIMID = T1.INVENTDIMIDDEFAULT and xx.DATAAREAID = '220' 
LEFT JOIN INVENTDIM XX2 on xx2.INVENTDIMID = T2.INVENTDIMIDDEFAULT and xx2.DATAAREAID = '220'
LEFT JOIN INVENTDIM XX3 on xx3.INVENTDIMID = T3.INVENTDIMIDDEFAULT and xx3.DATAAREAID = '220'
where T1.STOPPED  + T2.STOPPED  + T3.STOPPED <> 0
order by 1
