SELECT  it.ITEMID, WMSLOCATIONIDDEFAULTRECEIPT
FROM	INVENTTABLE			it INNER JOIN 
		INVENTITEMLOCATION	itl ON it.itemid = itl.ITEMID INNER JOIN 
		INVENTDIM			id  ON id.INVENTDIMID = itl.INVENTDIMID and id.INVENTLOCATIONID = 'TJ-MAIN'
--where it.ITEMID = 'CRS603S3386X'
