SELECT	U.ID		[USER], 
		U.NAME		UNAME, 
		U.[ENABLE], 
		A.USER_		WORKER, 
		B.NAME		WNAME
FROM		USERINFO		U
LEFT JOIN	DIRPERSONUSER	A ON U.ID =  USER_
LEFT JOIN	DIRPARTYTABLE	B ON A.PERSONPARTY = B.RECID
ORDER BY 1

